export const NEXT_FORM_REGISTER = 'NEXT_FORM_REGISTER';
export const PREV_FORM_REGISTER = 'PREV_FORM_REGISTER';
export const SET_FORM_REGISTER_VALUE = 'SET_FORM_REGISTER_VALUE';
export const SET_PARTICIPANT_ID = 'SET_PARTICIPANT_ID';

export const NEXT_FORM_QUESTION = 'NEXT_FORM_QUESTION';
export const PREV_FORM_QUESTION = 'PREV_FORM_QUESTION';
export const SET_QUESTION_ANSWERS = 'SET_QUESTION_ANSWERS';